#!/usr/bin/env bash
#manage_my_process by either starting, stopping or restarting

command="$"

if [-z "$command" ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit
fi

if [ "$command" == "start" ]; then

    bash ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"

elif [ "$command" == "restart" ]; then

    "$0" stop >& /dev/null
    "$0" start >& /dev/null
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
