#!/usr/bin/env bash
# Displays Best School 10 times with Hi on 9th iteration

count=1
while [[ "$count" -le 9 ]]
do
	echo "Best School"
	count=$((count + 1))
	if [ $count == 9 ]; then
		echo "Hi"
	fi
done
