#!/usr/bin/env bash
# This script connects to the server using SSH with the given private key and user.

# SSH command to connect to the server
ssh -i ~/.ssh/school -o StrictHostKeyChecking=no ubuntu@100.26.132.37

